name: c3_creatorclub
description: "c3 - Creator Club App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  freezed_annotation: 3.1.0
  json_annotation: ^4.9.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.5.0
  cloud_functions: ^5.5.0
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  table_calendar: ^3.1.2
  flutter_chat_ui: 2.9.0
  flutter_chat_types: ^3.6.2
  file_selector: ^1.0.3
  mime: ^1.0.5
  flutter_chat_core: ^2.8.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  add_2_calendar: ^2.2.3
  provider: ^6.1.2
  pdfx: ^2.6.0
  http: ^1.2.2
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_stripe: ^12.0.2
  app_links: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  freezed: ^3.1.0
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  fonts:
    - family: Garet
      fonts:
        - asset: assets/fonts/garet_regular.ttf
          weight: 400
        - asset: assets/fonts/garet_bold.ttf
          weight: 700
  assets:
    - assets/fonts/
    - assets/logo.svg
    - assets/app_icon/

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon/c3_logo.png
