// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkZzFy3ZmDKwS-weDMfcdWwGyWlwrydDo',
    appId: '1:385391631548:web:b458126f5cbd8985fd84b9',
    messagingSenderId: '385391631548',
    projectId: 'c3club-app',
    authDomain: 'c3club-app.firebaseapp.com',
    storageBucket: 'c3club-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw8wzuHeEH1hUZ1-DBYGhsTaWXwbh4kt4',
    appId: '1:385391631548:android:f2a879f8e80f2badfd84b9',
    messagingSenderId: '385391631548',
    projectId: 'c3club-app',
    storageBucket: 'c3club-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXzhxJ3g0YRr0mcFY4BzobyZg_oXqIdA4',
    appId: '1:385391631548:ios:098d371cc53c8bf3fd84b9',
    messagingSenderId: '385391631548',
    projectId: 'c3club-app',
    storageBucket: 'c3club-app.firebasestorage.app',
    iosBundleId: 'com.c3.creatorclub',
  );
}
