import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'app.dart';
import 'package:flutter_stripe/flutter_stripe.dart' as stripe;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  debugPrint('Starting app...');
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  debugPrint('Firebase initialized.');
  // Don't block app start on Stripe init; handle errors gracefully.
  try {
    stripe.Stripe.publishableKey = const String.fromEnvironment(
      'STRIPE_PUBLISHABLE_KEY',
      defaultValue:
          'pk_test_51S6Ak52YPBrnauDZ4qozW0XLMwC7dOaHDdSQfhwoMDf8Vaqlxd9z36UYHp4Zo7xHdfWvgoCpN1LDmHnf22CJl5QB007XriDwK1',
    );
    await stripe.Stripe.instance.applySettings();
    debugPrint('Stripe initialized.');
  } catch (e, st) {
    debugPrint('Stripe initialization failed (non-fatal): $e\n$st');
  }
  // Use C3Root (which wraps C3App with the deep-link handler) so custom scheme
  // links like c3creatorclub://membership/success are translated into
  // internal GoRouter paths (e.g. /membership/success).
  runApp(const ProviderScope(child: C3Root()));
}

class FirebaseCheckScreen extends StatefulWidget {
  const FirebaseCheckScreen({super.key});

  @override
  State<FirebaseCheckScreen> createState() => _FirebaseCheckScreenState();
}

class _FirebaseCheckScreenState extends State<FirebaseCheckScreen> {
  String _status = 'Checking Firebase...';

  @override
  void initState() {
    super.initState();
    _verifyFirebase();
  }

  Future<void> _verifyFirebase() async {
    try {
      // If initializeApp completed, options should be available.
      final options = DefaultFirebaseOptions.currentPlatform;
      setState(() {
        _status =
            '✅ Firebase initialized.\n'
            'Project: ${options.projectId}\n'
            'App ID: ${options.appId}';
      });
    } catch (e) {
      setState(() {
        _status = '❌ Firebase not initialized: $e';
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Firebase Check')),
      body: Center(
        child: Text(
          _status,
          textAlign: TextAlign.center,
          style: const TextStyle(fontSize: 16),
        ),
      ),
    );
  }
}
