import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'app.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const ProviderScope(child: C3App()));
}

class FirebaseCheckScreen extends StatefulWidget {
  const FirebaseCheckScreen({super.key});

  @override
  State<FirebaseCheckScreen> createState() => _FirebaseCheckScreenState();
}

class _FirebaseCheckScreenState extends State<FirebaseCheckScreen> {
  String _status = 'Checking Firebase...';

  @override
  void initState() {
    super.initState();
    _verifyFirebase();
  }

  Future<void> _verifyFirebase() async {
    try {
      // If initializeApp completed, options should be available.
      final options = DefaultFirebaseOptions.currentPlatform;
      setState(() {
        _status =
            '✅ Firebase initialized.\n'
            'Project: ${options.projectId}\n'
            'App ID: ${options.appId}';
      });
    } catch (e) {
      setState(() {
        _status = '❌ Firebase not initialized: $e';
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Firebase Check')),
      body: Center(
        child: Text(
          _status,
          textAlign: TextAlign.center,
          style: const TextStyle(fontSize: 16),
        ),
      ),
    );
  }
}
